version: '3'

services:
  db-scores:
    image: mysql:8.3.0
    restart: always
    container_name: db-dev
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scores
      MYSQL_USER: user
      MYSQL_PASSWORD: magicman
    volumes:
      - db-scores-data:/var/lib/mysql
    ports:
      - 3050:3306
      
volumes:
    db-scores-data: