version: '3'

services:
  scores-db:
    image: mongo
    ports:
      - "27050:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=competitions
    volumes:
      - db-scores-data:/data/db

volumes:
   db-scores-data: