version: '3'

services:
  rabbitmq:
      image: rabbitmq:3.13-management-alpine
      container_name: webs5-rabbitmq
      restart: always
      ports:
        - "5672:5672"  
        - "15672:15672" 