version: '3'

services:
  db-targets:
    image: mysql:8.3.0
    restart: always
    container_name: db-dev
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: targets
      MYSQL_USER: user
      MYSQL_PASSWORD: magicman
    volumes:
      - db-targets-data:/var/lib/mysql
    ports:
      - 2050:3306

  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management UI

volumes:
  db-targets-data:
